# Generated by Django 4.1.4 on 2023-02-21 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
