# Generated by Django 4.1.4 on 2023-03-06 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='activity',
            name='is_display',
            field=models.BooleanField(default=False),
        ),
    ]
